---
- type: replace
  path: /releases/-
  value:
    name: bosh-docker-cpi
    version: "0.0.3"
    url: https://bosh.io/d/github.com/cppforlife/bosh-docker-cpi-release?v=0.0.3
    sha1: 9eb1457a5f268a8e3a21765d151366e28f7d5ea3

- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value:
    name: docker_cpi
    release: bosh-docker-cpi

# unused values should be overwritten via Director's cpi config
- type: replace
  path: /instance_groups/name=bosh/properties/docker_cpi?
  value:
    docker:
      host: unused
      tls:
        ca: unused
        certificate: unused
        private_key: unused
    agent:
      mbus: nats://nats:((nats_password))@((internal_ip)):4222
      blobstore:
        provider: dav
        options:
          endpoint: http://((internal_ip)):25250
          user: agent
          password: ((blobstore_agent_password))
