#!/bin/bash

fly -t bucc set-pipeline -c ci/deploy-cf-pipeline.yml -p deploy-cf
fly -t bucc set-pipeline -c ci/deploy-kibosh-pipeline.yml -p deploy-kibosh
fly -t bucc set-pipeline -c ci/manage-accounts-pipeline.yml -p manage-accounts
