#!/usr/bin/env bash

set -euo pipefail

if [[ $# -eq 0 ]]; then
  echo "Usage: $(basename $0) number [command]"
  exit 1
fi

n=$1

if [[ $# -gt 1 ]]; then
  gcloud --account="training.hol.$n@gmail.com" --project="handson-lab-user$n" alpha cloud-shell ssh --command="$2"
else
  gcloud --account="training.hol.$n@gmail.com" --project="handson-lab-user$n" alpha cloud-shell ssh
fi
