#!/usr/bin/env bash

set -euo pipefail

if [[ ! -v CLOUD_SHELL ]]; then
  echo "This script removes all changes from a git-backed cloud-shell home directory."
  echo "Since I don't see the \$CLOUD_SHELL variable defined, I don't believe we're in a cloud shell."
  echo "Cowardly refusing to proceed."
  exit 1
fi

export GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no'

git clean -df
git reset --hard
git lfs install
git pull
git lfs checkout

. ~/.bashrc

cf login -u $PWS_USER -p $PWS_PASSWORD -a api.run.pivotal.io
